<?php
/**
 * @file
 * Module provides automatic timezone detection via javascript.
 */

// jsTimezeDetect library information.
define('TIMEZONE_DETECT_LIBRARY_WEBSITE', 'http://pellepim.bitbucket.org/jstz/');
define('TIMEZONE_DETECT_LIBRARY_FILENAME', 'jstz.js');
define('TIMEZONE_DETECT_LIBRARY_DOWNLOAD_URL', 'https://bitbucket.org/pellepim/jstimezonedetect/raw/default/jstz.js');

// Detection modes configured via administration form.
// Note these are strings instead of integers because system_settings_form()
// saves variable values as strings.
define('TIMEZONE_DETECT_MODE_DEFAULT', '0');
define('TIMEZONE_DETECT_MODE_LOGIN', '1');
define('TIMEZONE_DETECT_MODE_ALWAYS', '2');

/**
 * Implements hook_menu().
 */
function timezone_detect_menu() {

  // Admin settings.
  $items['admin/config/regional/timezone_detect'] = array(
    'title' => 'Timezone Detect',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('timezone_detect_admin_form'),
    'access arguments' => array('administer site configuration'),
    'description' => 'Configure timezone detection settings.',
    'file' => 'timezone_detect.admin.inc',
  );

  $items['admin/config/regional/timezone_detect/admin'] = array(
    'title' => 'Timezone Detect',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  // Ajax callback function to set current user's timezone.
  $items['timezone-detect/ajax/set-timezone'] = array(
    'title' => 'Update session timezone',
    'page callback' => 'timezone_detect_set_timezone',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_library().
 */
function timezone_detect_library() {
  $path = drupal_get_path('module', 'timezone_detect');
  return array(
    'jstz' => array(
      'title' => t('jsTimezoneDetect'),
      'website' => TIMEZONE_DETECT_LIBRARY_WEBSITE,
      'version' => '1.0.5',
      'js' => array(
        $path . '/' . TIMEZONE_DETECT_LIBRARY_FILENAME => array(),
      ),
    ),
  );
}

/**
 * Implements hook_user_login().
 */
function timezone_detect_user_login(&$edit, $account) {
  if (variable_get('timezone_detect_mode') === TIMEZONE_DETECT_MODE_LOGIN || empty($account->timezone)) {
    // Set session flag to update user's timezone. Note that we cannot add the
    // js directly from this function, as the user is redirected after this
    // hook fires.
    $_SESSION['timezone_detect']['update_timezone'] = TRUE;
  }
}

/**
 * Implements hook_page_build().
 */
function timezone_detect_page_build(&$page) {
  // Include the javascript only when appropriate.
  if (isset($_SESSION['timezone_detect']['update_timezone']) || (!user_is_anonymous() && variable_get('timezone_detect_mode') === TIMEZONE_DETECT_MODE_ALWAYS)) {
    timezone_detect_add_js();
  }
}

/**
 * Ajax callback function to set current user's timezone.
 */
function timezone_detect_set_timezone() {
  global $user;

  // If they are logged in, set some data.
  if (!user_is_anonymous()) {
    // Check for $_POST data.
    // Timezone should be an IANA/Olson timezone id provided via $_POST.
    if (!isset($_POST['timezone'])) {
      watchdog('timezone_detect', 'Attempting to set timezone for user @uid, but no timezone found in $_POST data; aborting.', array('@uid' => $user->uid), WATCHDOG_ERROR);
      return '';
    }
    $timezone = check_plain($_POST['timezone']);

    // Keep track of the last submitted timezone in case it's not valid so that
    // we don't keep POSTing it on every request.
    $_SESSION['timezone_detect']['current_timezone'] = $timezone;

    // Check valid timezone id.
    $zone_list = timezone_identifiers_list();
    if (!in_array($timezone, $zone_list)) {
      watchdog('timezone_detect', 'Attempting to set timezone for user @uid to @timezone, but that does not appear to be a valid timezone id; aborting.', array('@uid' => $user->uid, '@timezone' => $timezone), WATCHDOG_ERROR);
      return '';
    }

    // Save timezone to account.
    $account = user_load($user->uid);
    $edit['timezone'] = $timezone;
    user_save($account, $edit);
    if (variable_get('timezone_detect_success_watchdog', TRUE)) {
      watchdog('timezone_detect', 'Set timezone for user @uid to @timezone.', array('@uid' => $user->uid, '@timezone' => $timezone));
    }
  }

  // Unset session flag regarldess of whether they are logged in or not to avoid
  // repeated attempts at this process that are likely to fail.
  unset($_SESSION['timezone_detect']['update_timezone']);
}

/**
 * Add the javascript that will update the user's timezone via ajax callback.
 */
function timezone_detect_add_js() {
  $added = &drupal_static(__FUNCTION__, FALSE);
  if (!$added) {
    // Add library js.
    drupal_add_library('timezone_detect', 'jstz');

    // Add helper js.
    $helper_js = drupal_get_path('module', 'timezone_detect') . '/timezone_detect.js';
    drupal_add_js($helper_js);

    // Store the current timezone for comparison.
    $timezone = !empty($_SESSION['timezone_detect']['current_timezone']) ? $_SESSION['timezone_detect']['current_timezone'] : $GLOBALS['user']->timezone;
    $setting = array(
      'timezone_detect' => array(
        'current_timezone' => $timezone,
      ),
    );
    drupal_add_js($setting, 'setting');

    // Mark as added so we don't do it again.
    $added = TRUE;
  }
}
  /**
 * Implementation of hook_user().
 */
function mymodule_user($type, &$edit, &$user, &$timezone, $category = NULL) {  
  switch ($type) {
    case 'view':
      # code...
    $items['Last login'] = array( 
      'title' => t('Last login'),
        'value' => format_date($user->login,'small'),
        'class' => 'mymodule',
        );
        return array(t('History') => $items);

      break;
    }
    function drupal_set_message($message = NULL, $type = 'status', $repeat = TRUE) {  
   if ($message) {  
    if (!isset($_SESSION ['messages'])) {
      $_SESSION ['messages'] = array(); 
    }

    if (!isset($_SESSION ['messages'][$type])) {
      $_SESSION ['messages'][$type] = array();
    }

    if ($repeat || !in_array($message, $_SESSION ['messages'][$type])) {  
      $_SESSION ['messages'][$type][] = $message;  
    }
  }

  // messages not set when DB connection fails
  return isset($_SESSION ['messages']) ? $_SESSION ['messages'] : NULL; 
}

    function drupal_get_user_timezone() { 
   global $user; 
   if (variable_get('configurable_timezones', 1) && $user->uid && $user->timezone) {  
   return $user->timezone; 
}
else { 

  return variable_get('date_default_timezone', @date_default_timezone_get()); }
}
    }

function blockanimate_help($path, $arg) {
  switch ($path) {
    case 'admin/help#blockanimate':
      return blockanimate_get_help_message();
  }
}

/**
 * Implements hook_permission().
 */
function blockanimate_permission() {
  return array(
    'administer block animate' => array(
      'title' => t('Configure Block Animate animations.'),
      'description' => t("Configure Animate CSS animations for website's blocks."),
    ),
  );
}

/**
 * Implements theme_preprocess_block().
 */
function blockanimate_preprocess_block(&$vars) {
  $block = $vars['block'];
  _blockanimate_add_js_classes_and_attributes($block, $vars);
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Extend panel block's classes and attributes with animate css classes
 * and attributes.
 */
function blockanimate_preprocess_panels_pane(&$vars) {
  if ($vars['pane']->type != 'block') {
    return;
  }
  // Infer the block's $module and $delta from the pane subtype.
  $block_parts = explode('-', $vars['pane']->subtype);
  // Load the block based on the block parts.
  $block = block_load($block_parts[0], $block_parts[1]);
  // Add a generic 'module type' pane class.
  $vars['classes_array'][] = drupal_html_class('pane-' . $block->module);
  _blockanimate_add_js_classes_and_attributes($block, $vars);
}

/**
 * Extend block's classes and attributes.
 *
 * Extend block's classes with animate css classes and block's attributes with
 * wow.js attributes. It adds the required Javascript file to create and
 * initialize the WOW Javascript object.
 */
function _blockanimate_add_js_classes_and_attributes($block, &$vars) {
  if (isset($block->animate_css_class) && ($block->animate_css_class != 'none') && ($block->animate_css_class != '')) {
    // If an animation exists, we create and activate the WOW Javascript object.
    $js_path = drupal_get_path('module', 'blockanimate') . '/js/blockanimate.js';
    drupal_add_js($js_path);
    // Add the wow attributes to the block attributes if needed.
    $animate_attributes = _blockanimate_get_block_attributes($block);
    $vars['attributes_array'] = array_merge($vars['attributes_array'], $animate_attributes);
    // And add the Animate CSS classes to the block classes if needed.
    $animate_classes = _blockanimate_get_block_classes($block);
    $vars['classes_array'] = array_merge($vars['classes_array'], $animate_classes);
  }
}

/**
 * Implements hook_form_alter().
 *
 * Alter block edit form to add block's animate css and wow JS configuration
 * fields.
 */
function blockanimate_form_alter(&$form, &$form_state, $form_id) {
  if (user_access('administer block animate') && ($form_id == 'block_admin_configure' || $form_id == 'block_add_block_form')) {
    // Load statically cached block object used to display the form.
    $block = block_load($form['module']['#value'], $form['delta']['#value']);
    _blockanimate_add_form_fieldset($form);
    _blockanimate_add_form_animate_css_fields($form, $block);
    _blockanimate_add_form_wow_js_fields($form, $block);
    $form['#submit'][] = 'blockanimate_form_submit';
  }
}

/**
 * Helper function: adds a new fieldset to the block configuration form.
 */
function _blockanimate_add_form_fieldset(&$form) {
  $form['settings']['animate_css'] = array(
    '#type' => 'fieldset',
    '#title' => t('Animate CSS Animation'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
}

/**
 * Helper function.
 *
 * Adds Animate CSS related fields to the block configuration form.
 */
function _blockanimate_add_form_animate_css_fields(&$form, $block) {
  $form['settings']['animate_css']['animate_css_class'] = array(
    '#type' => 'select',
    '#title' => t('Select Animation'),
    '#options' => _blockanimate_animation_types_form_options(),
    '#default_value' => $block->animate_css_class,
    '#description' => t('Select the Animate CSS animation you wish to apply to this block.'
    ),
  );
  $form['settings']['animate_css']['animate_css_infinite'] = array(
    '#type' => 'checkbox',
    '#title' => t('Apply an infinite loop to this animation.'),
    '#description' => t("This option can't be checked if you set the Animation iteration option."),
    '#default_value' => $block->animate_css_infinite,
    '#element_validate' => array(
      'blockanimate_validate_infinite_loop_checkbox',
    ),
  );
}

/**
 * Helper function: adds WOW JS related fields to the block configuration form.
 */
function _blockanimate_add_form_wow_js_fields(&$form, $block) {
  $form['settings']['animate_css']['animate_css_wow_duration'] = array(
    '#type' => 'textfield',
    '#title' => t('Animation Duration.'),
    '#description' => t("Change the default animation's duration. Leave blank for default duration (1 second). Units: seconds. Example: 10 (seconds)"),
    '#default_value' => ((floatval($block->animate_css_wow_duration) > 0) ?
      $block->animate_css_wow_duration : ''),
    '#field_suffix' => 'seconds',
    '#element_validate' => array(
      'blockanimate_validate_positive_float_field',
    ),
    '#prefix' => '<br/><h2>Advanced Options</h2>',
  );
  $form['settings']['animate_css']['animate_css_wow_delay'] = array(
    '#type' => 'textfield',
    '#title' => t('Animation Delay.'),
    '#description' => t("Change the default animation's delay. Leave blank for default delay (0 seconds). Units: seconds. Example: 5 (seconds)"),
    '#default_value' => ((floatval($block->animate_css_wow_delay) > 0) ?
      $block->animate_css_wow_delay : ''),
    '#field_suffix' => 'seconds',
    '#element_validate' => array(
      'blockanimate_validate_positive_float_field',
    ),
  );
  $form['settings']['animate_css']['animate_css_wow_offset'] = array(
    '#type' => 'textfield',
    '#title' => t('Animation Offset.'),
    '#description' => t("Change the default offset. Leave blank for default offset (0 pixels). Units: pixels. Example: 100 (pixels)"),
    '#default_value' => ((intval($block->animate_css_wow_offset) > 0) ?
      $block->animate_css_wow_offset : ''),
    '#field_suffix' => 'pixels',
    '#element_validate' => array('element_validate_integer_positive'),
  );
  $form['settings']['animate_css']['animate_css_wow_iteration'] = array(
    '#type' => 'textfield',
    '#title' => t('Animation Iteration.'),
    '#description' => t("Change the default number of animation iterations. Leave blank for default number of iterations (1 iteration). If you set this option, the 'Apply an infinite loop to this animation' can't be set. Units: number of iterations. Example: 2 (iterations)"),
    '#default_value' => ((intval($block->animate_css_wow_iteration) > 0) ?
      $block->animate_css_wow_iteration : ''),
    '#field_suffix' => 'iterations',
    '#element_validate' => array('element_validate_integer_positive'),
  );
}

/**
 * Helper function: validates optional positive float form fields.
 */
function blockanimate_validate_positive_float_field($element, &$form_state, $form) {
  $field_value = $element['#value'];
  if (strlen($field_value) > 0) {
    // The field is only validated when not left blank.
    $is_not_numeric = !is_numeric($field_value);
    $is_not_float_value = (strval(floatval($field_value)) != $field_value);
    $is_not_positive = (floatval($field_value) <= 0);
    if ($is_not_numeric || $is_not_float_value || $is_not_positive) {
      form_error($element, t('@field_name This field must be a positive float number. Examples: 0.5, 2, 4.35', array(
          '@field_name' => $element['#title'],
        )
      ));
    }
  }
}

/**
 * Helper function.
 *
 * Validates the infinite loop checkbox. This option can't be
 * checked if the Animate Iteration option is set.
 */
function blockanimate_validate_infinite_loop_checkbox($element, &$form_state, $form) {
  $field_value = $element['#value'];
  if ($field_value) {
    $animate_css_iteration = $form_state['values']['animate_css_wow_iteration'];
    if (strlen($animate_css_iteration) > 0) {
      form_error($element, t("@field_name This option can't be checked when you set the Animation Iteration option.", array(
          '@field_name' => $element['#title'],
        )
      ));
    }
  }
}

/**
 * Helper function.
 *
 * Additional submit callback for block configuration pages.
 * Save supplied block CSS classes and block attributes.
 */
function blockanimate_form_submit($form, &$form_state) {
  $form_id = $form_state['values']['form_id'];
  if ($form_id == 'block_admin_configure' || $form_id == 'block_add_block_form') {
    $animate_css_class = $form_state['values']['animate_css_class'];
    $animate_css_infinite = (($animate_css_class != 'none') && (strlen($form_state['values']['animate_css_wow_iteration']) == 0)) ?
      $form_state['values']['animate_css_infinite'] : 0;
    $animate_css_duration = _blockanimate_get_db_value_for_optional_field($animate_css_class,
      $form_state['values']['animate_css_wow_duration']);
    $animate_css_delay = _blockanimate_get_db_value_for_optional_field($animate_css_class,
      $form_state['values']['animate_css_wow_delay']);
    $animate_css_offset = _blockanimate_get_db_value_for_optional_field($animate_css_class,
      $form_state['values']['animate_css_wow_offset']);
    $animate_css_iteration = _blockanimate_get_db_value_for_optional_field($animate_css_class,
      $form_state['values']['animate_css_wow_iteration']);
    $field_values = array(
      'animate_css_class' => $animate_css_class,
      'animate_css_infinite' => $animate_css_infinite,
      'animate_css_wow_duration' => $animate_css_duration,
      'animate_css_wow_delay' => $animate_css_delay,
      'animate_css_wow_offset' => $animate_css_offset,
      'animate_css_wow_iteration' => $animate_css_iteration,
    );
    if (user_access('administer blocks') && !empty($field_values)) {
      db_update('block')
        ->fields($field_values)
        ->condition('module', $form_state['values']['module'])
        ->condition('delta', $form_state['values']['delta'])
        ->execute();
      // Flush all context module cache to use the updated block classes.
      if (module_exists('context')) {
        cache_clear_all('context', 'cache', TRUE);
      }
    }
  }
}

/**
 * Helper function.
 *
 * Returns value to store in DB for optional field.
 */
function _blockanimate_get_db_value_for_optional_field($animate_css_class, $field_value) {
  return (($animate_css_class != 'none') && (strlen($field_value) > 0)) ?
    $field_value : -1;
}

/**
 * Helper function.
 *
 * Returns an array of Animate CSS classes for a block which
 * has an animation associated to.
 */
function _blockanimate_get_block_classes($block) {
  if ($block->animate_css_infinite) {
    $animate_classes = array(
      'animated',
      'infinite',
      'wow',
      check_plain($block->animate_css_class),
    );
  }
  else {
    $animate_classes = array(
      'animated',
      'wow',
      check_plain($block->animate_css_class),
    );
  }
  return $animate_classes;
}

/**
 * Helper function.
 *
 * Returns an array of WOW Javascript attributes for a block
 * which has an animation associated to.
 */
function _blockanimate_get_block_attributes($block) {
  $block_attributes = array();
  if ($block->animate_css_wow_duration != (-1)) {
    $block_attributes['data-wow-duration'] = check_plain($block->animate_css_wow_duration) . 's';
  }
  if ($block->animate_css_wow_delay != (-1)) {
    $block_attributes['data-wow-delay'] = check_plain($block->animate_css_wow_delay) . 's';
  }
  if ($block->animate_css_wow_offset != (-1)) {
    $block_attributes['data-wow-offset'] = check_plain($block->animate_css_wow_offset);
  }
  if ($block->animate_css_wow_iteration != (-1)) {
    $block_attributes['data-wow-iteration'] = check_plain($block->animate_css_wow_iteration);
  }
  return $block_attributes;
}

/**
 * Helper function.
 *
 * Returns the Animate CSS animation effects the user can
 * select from the select list in the block's configuration page.
 */
function _blockanimate_animation_types_form_options() {
  return array(
    'none'   => t('-- No animation --'),
    'bounce' => t('Bounce'),
    'flash'  => t('Flash'),
    'pulse'  => t('Pulse'),
    'rubberBand' => t('Rubber Band'),
    'shake' => t('Shake'),
    'swing' => t('Swing'),
    'tada' => t('Tada'),
    'wobble' => t('Wobble'),
    'bounceIn' => t('Bounce In'),
    'bounceInDown' => t('Bounce In Down'),
    'bounceInLeft' => t('Bounce In Left'),
    'bounceInRight' => t('Bounce In Right'),
    'bounceInUp' => t('Bounce In Up'),
    'bounceOut' => t('Bounce Out'),
    'bounceOutDown' => t('Bounce Out Down'),
    'bounceOutLeft' => t('Bounce Out Left'),
    'bounceOutRight' => t('Bounce Out Right'),
    'bounceOutUp' => t('Bounce Out Up'),
    'fadeIn' => t('Fade In'),
    'fadeInDown' => t('Fade In Down'),
    'fadeInDownBig' => t('Fade In Down Big'),
    'fadeInLeft' => t('Fade In Left'),
    'fadeInLeftBig' => t('Fade In Left Big'),
    'fadeInRight' => t('Fade In Right'),
    'fadeInRightBig' => t('Fade In Right Big'),
    'fadeInUp' => t('Fade In Up'),
    'fadeInUpBig' => t('Fade In Up Big'),
    'fadeOut' => t('Fade Out'),
    'fadeOutDown' => t('Fade Out Down'),
    'fadeOutDownBig' => t('Fade Out Down Big'),
    'fadeOutLeft' => t('Fade Out Left'),
    'fadeOutLeftBig' => t('Fade Out Left Big'),
    'fadeOutRight' => t('Fade Out Right'),
    'fadeOutRightBig' => t('Fade Out Right Big'),
    'fadeOutUp' => t('Fade Out Up'),
    'fadeOutUpBig' => t('Fade Out Up Big'),
    'flipInX' => t('Flip In X'),
    'flipInY' => t('Flip In Y'),
    'flipOutX' => t('Flip Out X'),
    'flipOutY' => t('Flip Out Y'),
    'lightSpeedIn' => t('Light Speed In'),
    'lightSpeedOut' => t('Light Speed Out'),
    'rotateIn' => t('Rotate In'),
    'rotateInDownLeft' => t('Rotate In Down Left'),
    'rotateInDownRight' => t('Rotate In Down Right'),
    'rotateInUpLeft' => t('Rotate In Up Left'),
    'rotateInUpRight' => t('Rotate In Up Right'),
    'rotateOut' => t('Rotate Out'),
    'rotateOutDownLeft' => t('Rotate Out Down Left'),
    'rotateOutDownRight' => t('Rotate Out Down Right'),
    'rotateOutUpLeft' => t('Rotate Out Up Left'),
    'rotateOutUpRight' => t('Rotate Out Up Right'),
    'hinge' => t('Hinge'),
    'rollIn' => t('Roll In'),
    'rollOut' => t('Roll Out'),
    'zoomIn' => t('Zoon In'),
    'zoomInDown' => t('Zoom In Down'),
    'zoomInLeft' => t('Zoom In Left'),
    'zoomInRight' => t('Zoom In Right'),
    'zoomInUp' => t('Zoom In Up'),
    'zoomOut' => t('Zoom Out'),
    'zoomOutDown' => t('Zoom Out Down'),
    'zoomOutLeft' => t('Zoom Out Left'),
    'zoomOutRight' => t('Zoom Out Right'),
    'zoomOutUp' => t('Zoom Out Up'),
    'slideInDown' => t('Slide In Down'),
    'slideInLeft' => t('Slide In Left'),
    'slideInRight' => t('Slide In Right'),
    'slideInUp' => t('Slide In Up'),
    'slideOutDown' => t('Slide Out Down'),
    'slideOutLeft' => t('Slide Out Left'),
    'slideOutRight' => t('Slide Out Right'),
    'slideOutUp' => t('Slide Out Up'),
  );
}

/**
 * Helper function.
 *
 * Returns the modules' help text for Drupal's administration
 * help section.
 */
function blockanimate_get_help_message() {
  $message = '<p>';
  $message .= t("The Block Animate module adds a new fieldset with a few new options to Drupal's block configuration form. Using these options you can set an animation for each of your website's blocks, the animation duration, the number of times the animation will be executed, and so on.");
  $message .= '</p>';
  $message .= '<p>';
  $message .= t("These animations are provided by the Animate CSS library. There is a lot of different animations available to choose from. These animations are CSS3 animations, so they're cross browser animations.");
  $message .= '</p>';
  $message .= '<p>';
  $message .= t("This module uses the WOW Javascript library too. Thanks to this library, these animations are shown when the blocks become visible as you scroll down the page.");
  $message .= '</p>';
  return $message;
}

function mymodule_admin_configure($form, &$form_state, $module, $delta) {
  $block = mymodule_load($module, $delta);
  $form['module'] = array(
    '#type' => 'value',
    '#value' => $block->module,
  );
  $form['delta'] = array(
    '#type' => 'value',
    '#value' => $block->delta,
  );
 

  $form['settings']['title'] = array(
    '#type' => 'textfield',
    '#title' => t('Block title'),
    '#maxlength' => 255,
    '#description' => $block->module == 'block' ? t('The title of the block as shown to the user.') : t('Override the default title for the block. Use <em>!placeholder</em> to display no title, or leave blank to use the default block title.', array('!placeholder' => '&lt;none&gt;')),
    '#default_value' => isset($block->title) ? $block->title : '',
    '#weight' => -19,
  );

  // Module-specific block configuration.
  if ($settings = module_invoke($block->module, 'block_configure', $block->delta)) {
    foreach ($settings as $k => $v) {
      $form['settings'][$k] = $v;
    }
  }

  // Region settings.
  $form['regions'] = array(
    '#type' => 'fieldset',
    '#title' => t('Region settings'),
    '#collapsible' => FALSE,
    '#description' => t('Specify in which themes and regions this block is displayed.'),
    '#tree' => TRUE,
  );

   
  // Visibility settings.
  $form['visibility_title'] = array(
    '#type' => 'item',
    '#title' => t('Visibility settings'),
  );
  $form['visibility'] = array(
    '#type' => 'vertical_tabs',
    '#attached' => array(
      'js' => array(drupal_get_path('module', 'block') . '/block.js'),
    ),
  );

  // Per-path visibility.
  $form['visibility']['path'] = array(
    '#type' => 'fieldset',
    '#title' => t('Pages'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#group' => 'visibility',
    '#weight' => 0,
  );

  $access = user_access('use PHP for settings');
  if (isset($block->visibility) && $block->visibility == BLOCK_VISIBILITY_PHP && !$access) {
    $form['visibility']['path']['visibility'] = array(
      '#type' => 'value',
      '#value' => BLOCK_VISIBILITY_PHP,
    );
    $form['visibility']['path']['pages'] = array(
      '#type' => 'value',
      '#value' => isset($block->pages) ? $block->pages : '',
    );
  }
  else {
    $options = array(
      BLOCK_VISIBILITY_NOTLISTED => t('All pages except those listed'),
      BLOCK_VISIBILITY_LISTED => t('Only the listed pages'),
    );
    $description = t("Specify pages by using their paths. Enter one path per line. The '*' character is a wildcard. Example paths are %blog for the blog page and %blog-wildcard for every personal blog. %front is the front page.", array('%blog' => 'blog', '%blog-wildcard' => 'blog/*', '%front' => '<front>'));

    if (module_exists('php') && $access) {
      $options += array(BLOCK_VISIBILITY_PHP => t('Pages on which this PHP code returns <code>TRUE</code> (experts only)'));
      $title = t('Pages or PHP code');
      $description .= ' ' . t('If the PHP option is chosen, enter PHP code between %php. Note that executing incorrect PHP code can break your Drupal site.', array('%php' => '<?php ?>'));
    }
    else {
      $title = t('Pages');
    }
    $form['visibility']['path']['visibility'] = array(
      '#type' => 'radios',
      '#title' => t('Show block on specific pages'),
      '#options' => $options,
      '#default_value' => isset($block->visibility) ? $block->visibility : BLOCK_VISIBILITY_NOTLISTED,
    );
    $form['visibility']['path']['pages'] = array(
      '#type' => 'textarea',
      '#title' => '<span class="element-invisible">' . $title . '</span>',
      '#default_value' => isset($block->pages) ? $block->pages : '',
      '#description' => $description,
    );
  }

  // Per-role visibility.
  $default_role_options = db_query("SELECT rid FROM {block_role} WHERE module = :module AND delta = :delta", array(
    ':module' => $block->module,
    ':delta' => $block->delta,
  ))->fetchCol();
  $role_options = array_map('check_plain', user_roles());
  $form['visibility']['role'] = array(
    '#type' => 'fieldset',
    '#title' => t('Roles'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#group' => 'visibility',
    '#weight' => 10,
  );
  $form['visibility']['role']['roles'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Show block for specific roles'),
    '#default_value' => $default_role_options,
    '#options' => $role_options,
    '#description' => t('Show this block only for the selected role(s). If you select no roles, the block will be visible to all users.'),
  );

  // Per-user visibility.
  $form['visibility']['user'] = array(
    '#type' => 'fieldset',
    '#title' => t('Users'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#group' => 'visibility',
    '#weight' => 20,
  );
  $form['visibility']['user']['custom'] = array(
    '#type' => 'radios',
    '#title' => t('Customizable per user'),
    '#options' => array(
      BLOCK_CUSTOM_FIXED => t('Not customizable'),
      BLOCK_CUSTOM_ENABLED => t('Customizable, visible by default'),
      BLOCK_CUSTOM_DISABLED => t('Customizable, hidden by default'),
    ),
    '#description' => t('Allow individual users to customize the visibility of this block in their account settings.'),
    '#default_value' => isset($block->custom) ? $block->custom : BLOCK_CUSTOM_FIXED,
  );

  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save block'),
  );

  return $form;
}
?>